# nixpacks.toml
# https://nixpacks.com/docs/configuration/file

[variables]
NIXPACKS_BUN_VERSION = '1'
NIXPACKS_NODE_PKG_MANAGER = 'bun'
CI = 'true'
NO_COLOR = '1'
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['bun']

[phases.install]
onlyIncludeFiles = [
  'package.json',
]
cmds = ['bun install']

[phases.build]
dependsOn = ['install']
cmds = ['bun run build']

[start]
dependsOn = ['build']
onlyIncludeFiles = ['.output']
cmd = 'bun run .output/server/index.mjs'
